language: python
python:
- 3.6
- 3.5
- 3.4
- 2.7
install: pip install -U tox-travis
script: tox
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: gabrielebarbieri
  password:
    secure: 0tRrYc3Nn3eNAfDIL46YHMUXmuldT01OTRGLRUJQrYNUQJJ4SGTcms9OCyMilFKeZ+aIuUd4yQiXSQgei7Wv6NPIaGfCBjmJChDKaZK3SoY2IrNVEpRQr+z0UKWY4i3qLr+Mk8kV3MAyAZjcG1+h6nX7JPQPmf5XLkmWU0XZ7bydke0ZSlVAvclvA1rsO2IO1/W17EVbQhewL28Wt74fs3KnNmTLBavzPTi/x52SCB2Zw03hxPhdHpI4YmxG7j4YiZ/MZACGozegaxoMsmMVC78lSDPfV7qi1TJAnxJER+kJBgPXtO3kZlTGDxQR7TIij2AcsWBfWyW/cPmJYB3Xv6dUSk8hH90kml+mhpUsp6yzGLTKlRSdDfgNMb/POfH/1hIjW5Ehls9L3cOYwcdlqXvNS9PPX0Q0O2oof5Wmj/RP597IsuHunKeMVVUYfxfxbnnjJjhgozxzJky5lZxD35NEZ9+3+j7CWcr0GAT2+VXBqPOeQwdLlFtzOTvQ9oTVaDDKEqXOpTYkAKcJYsOuaDVIB0tdUsreKqtXDRT+/qyuE9pQRezXUXBecH8TSxWNRb9ljqmBARUgQrfVQxzemIDxk+t9ItyK4cGO4aE1sNcDlZRpycSc5mcRP/1kGnSfUJIqmKsQcKDXNYcvxeQii2udbTa8cXjKfzT6Om//Evs=
  on:
    tags: true
    repo: gabrielebarbieri/abletonlink
    python: 3.6
